### ISSUE TITLE
brak obrazka

### ISSUE THREAD

**Issue by forkerprostak** [grzegorzfrankowski/PizzeriaDaVinci#6]
cześć, zauważyłem że w sekcji dodatki brakuje wam obrazka. Zdaje się, że trzeba to poprawić

**Comment by grzegorzfrankowski** [comment]
commit ef8aa333c6679ac75b0d5b99faa616466330638c naprawia ten błąd

**Comment by grzegorzfrankowski** [comment]
ef8aa333c6679ac75b0d5b99faa616466330638c fixes #7
